name: IndexNow Submit

on:
  push:
    branches:
      - main
      - master

jobs:
  submit-to-indexnow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Enviar URLs para IndexNow
        run: |
          echo "Enviando IndexNow..."

          URLS=(
            "https://empresa.planosdesaudephs.com.br/"
            "https://empresa.planosdesaudephs.com.br/sobre.html"
            "https://empresa.planosdesaudephs.com.br/contato.html"
          )

          for URL in "${URLS[@]}"; do
            echo "Enviando $URL"
            curl "https://api.indexnow.org/submit?url=$URL&key=c4e0af9b9d594a0e90d9aabbaf022991"
          done
